baseURL = 'https://c.deryck2000.jp.eu.org/'
languageCode = 'ja-ja'
defaultContentLanguage = 'ja'
title = 'デデオチャンのサイト'
theme = 'terminal'
publishDir = "docs"

[params]
  author = "deryck2000"
  description = """デデオチャンの創作置き場"""
  github = "Deryck2000"
  url = "https://c.deryck2000.jp.eu.org/"
  rss = true
  lastmod = true
  location = "Japan"
    favicon = "/favicon.ico"
  avatar = "/dedeo_icon.gif"
  headerIcon = "/favicon.ico"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = false
      menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
contentTypeName = "/content/posts"
timeZone = "Asia/Tokyo"
[taxonomies]
  tag = "tags"
  category = "categories"
    [menu]
      [[menu.main]]
        identifier = "創作漫画"
        name = "創作漫画"
        url = "/tags/sosaku/"
[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

  [markup.goldmark.renderer]
  unsafe = true